### ISSUE TITLE
Simplify pipeline configuration

### ISSUE THREAD

**Issue by alecharp** [jenkinsci/jacked-plugin#2]
### What feature do you want to see added?

Currently, using the plugin within a Pipeline project requires to add this in the Jenkinsfile:

```
step([$class: 'jacked', scanName: 'alpine', severityType: 'medium', autoInstall: true])
```

It could be simplify and make the syntax easier like

```
jacked scanName: 'alpine', severityType: 'medium', autoInstall: true
```

for example. See https://www.jenkins.io/doc/developer/plugin-development/pipeline-integration/#defining-symbols.

**Comment by sairenchristianbuerano** [comment]
Thank you, @alecharp. I will enhance it to simplify the syntax. 😃👍

**Comment by sairenchristianbuerano** [comment]
I simplified the syntax and updated the plugin. 😃
